--cajeros automaticos
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (855,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (901,' baja california sur');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (321,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (232,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (980,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (538,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (515,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1098,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (224,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (529,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (813,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (79,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (276,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (234,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (412,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1138,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (196,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (729,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (197,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (98,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1052,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (189,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (747,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (591,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (441,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (533,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (790,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1137,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (845,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (248,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (367,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (436,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (728,' yucatan');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (843,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1106,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1127,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (444,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (32,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (862,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (955,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (491,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (828,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (364,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1048,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (50,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1002,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (78,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (644,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (370,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (479,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (172,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (904,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (211,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (289,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (707,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1024,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (340,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (195,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (723,'');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (574,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1179,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (468,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (582,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (157,'');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (209,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (700,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (133,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (730,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (304,'');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1098,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (967,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (666,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (333,' yucatan');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (506,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (590,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1028,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (521,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (209,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (309,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (96,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (542,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (53,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (288,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (982,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (437,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1042,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (62,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (374,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (611,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (578,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (298,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (998,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1130,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1021,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (88,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (370,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (852,' oaxaca');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1081,' guanajuato');
 INSERT INTO atm (nidsucursal_atm,sestado) VALUES (80,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1051,' oaxaca');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (287,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (555,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (908,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (966,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1019,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (666,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (858,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1052,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (942,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (758,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1174,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (55,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (992,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (727,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1105,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (135,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (935,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (114,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (416,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (745,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (988,' baja california sur');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (837,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (474,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (933,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1186,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (890,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (517,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (26,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (541,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (201,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1146,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1082,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (85,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (516,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (967,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (180,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (203,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (343,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (604,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (977,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (21,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (73,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (568,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1015,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (314,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (300,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (769,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (378,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (115,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (302,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (895,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (201,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (135,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (612,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (537,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (745,' oaxaca');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (502,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (803,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (438,' colima');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (299,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (701,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (351,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (391,' baja california sur');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (674,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (212,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (236,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (735,' oaxaca');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (101,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (110,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (872,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (218,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (14,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (660,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (733,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1144,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (591,' baja california sur');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (151,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1143,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (962,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (25,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (700,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (355,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (858,' colima');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (671,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1104,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (258,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (684,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (704,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1184,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1094,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (980,' oaxaca');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (692,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (391,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (739,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1107,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (755,' coahuila de zaragoza');
 INSERT INTO atm (nidsucursal_atm,sestado) VALUES (187,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (381,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (406,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (296,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (287,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (295,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1143,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (634,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1066,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1172,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (889,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (809,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1199,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (509,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (63,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (720,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1130,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (943,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (479,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (122,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (283,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (158,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (571,' baja california sur');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (339,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1030,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (864,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (986,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1055,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1060,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (436,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1024,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (523,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (615,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1065,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (592,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (214,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (571,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (465,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (935,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1032,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (670,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1180,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (482,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (141,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (137,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1184,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1150,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (31,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (718,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (524,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1046,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (137,' colima');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (144,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (355,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (793,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (581,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (254,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (289,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (592,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (687,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1062,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (459,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (360,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (702,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (899,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (334,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (82,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (337,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (438,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (911,' baja california sur');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (741,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (63,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (494,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (514,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (837,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (833,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (535,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (386,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (888,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (555,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1030,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (346,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (644,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (895,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1058,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1062,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (974,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (635,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (923,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (518,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (101,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (763,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (693,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (249,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1170,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (944,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (289,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (921,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (498,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1077,' zacatecas');
 INSERT INTO atm (nidsucursal_atm,sestado) VALUES (405,' tabasco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (24,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (590,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1020,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (175,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (13,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (650,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (817,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (158,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (790,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (250,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (378,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (156,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (296,' san luis potosí');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (661,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (767,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (246,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (639,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1026,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (401,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (139,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (926,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1149,' chihuahua');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (54,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (255,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (798,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (910,' veracruz de ignacio de la llave');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (291,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (593,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (547,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1141,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (619,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (490,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1062,' zacatecas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (645,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (946,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (931,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (334,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (877,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (762,' coahuila de zaragoza');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1069,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (553,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (242,' sonora');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (688,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (582,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (677,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (517,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (148,' michoacán de ocampo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (663,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (350,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (994,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (27,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (335,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (442,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1141,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1129,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (817,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (419,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (783,' distrito federal');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (535,' colima');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (196,' jalisco');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (378,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (161,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (459,' yucatán');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (356,' baja california sur');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (226,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (877,' chiapas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (305,' guerrero');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (98,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (353,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1114,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (517,' oaxaca');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (368,' guanajuato');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (94,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1098,' colima');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1072,' durango');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (762,' hidalgo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (831,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (872,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (485,' tamaulipas');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (912,' campeche');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (741,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (163,' quintana roo');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1104,' sinaloa');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (837,' morelos');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (617,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (144,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (907,' oaxaca');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (169,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (488,' puebla');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (165,' nuevo león');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (861,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (71,' tlaxcala');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (412,' baja california');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (276,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (551,' querétaro');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (951,'aguascalientes');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (791,' nayarit');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (408,' méxico');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (599,' chihuahua');
