--Cajeros automaticos
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (855,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (901,' Baja California Sur');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (321,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (232,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (980,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (538,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (515,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1098,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (224,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (529,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (813,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (79,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (276,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (234,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (412,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1138,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (196,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (729,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (197,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (98,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1052,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (189,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (747,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (591,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (441,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (533,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (790,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1137,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (845,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (248,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (367,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (436,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (728,' Yucatan');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (843,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1106,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1127,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (444,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (32,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (862,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (955,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (491,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (828,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (364,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1048,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (50,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1002,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (78,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (644,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (370,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (479,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (172,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (904,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (211,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (289,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (707,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1024,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (340,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (195,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (723,'');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (574,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1179,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (468,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (582,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (157,'');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (209,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (700,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (133,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (730,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (304,'');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1098,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (967,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (666,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (333,' Yucatan');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (506,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (590,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1028,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (521,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (209,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (309,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (96,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (542,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (35,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (53,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (288,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (982,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (437,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1042,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (62,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (374,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (611,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (578,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (298,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (998,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1130,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1021,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (88,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (370,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (852,' Oaxaca');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1081,' Guanajuato');
 INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (80,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1051,' Oaxaca');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (287,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (555,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (908,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (35,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (966,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1019,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (666,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (858,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1052,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (942,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (758,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1174,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (55,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (992,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (727,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1105,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (135,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (935,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (114,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (416,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (745,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (988,' Baja California Sur');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (837,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (474,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (933,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1186,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (890,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (517,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (26,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (541,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (201,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1146,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1082,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (35,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (85,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (516,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (967,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (180,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (203,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (343,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (604,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (977,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (21,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (73,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (568,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1015,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (314,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (300,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (769,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (378,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (115,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (302,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (895,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (201,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (135,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (612,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (537,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (745,' Oaxaca');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (502,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (803,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (438,' Colima');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (299,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (701,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (351,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (391,' Baja California Sur');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (674,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (212,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (236,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (735,' Oaxaca');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (101,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (110,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (872,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (218,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (14,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (660,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (733,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1144,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (591,' Baja California Sur');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (151,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1143,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (962,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (25,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (700,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (355,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (858,' Colima');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (671,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1104,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (258,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (684,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (704,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1184,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1094,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (980,' Oaxaca');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (692,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (391,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (739,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1107,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (755,' Coahuila de Zaragoza');
 INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (187,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (381,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (406,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (296,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (287,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (295,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1143,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (634,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1066,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1172,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (889,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (809,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1199,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (509,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (63,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (720,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1130,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (943,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (479,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (122,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (283,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (158,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (571,' Baja California Sur');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (339,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1030,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (864,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (986,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1055,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1060,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (436,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1024,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (523,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (615,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1065,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (592,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (214,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (571,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (465,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (935,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1032,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (670,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1180,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (482,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (141,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (137,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1184,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1150,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (31,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (718,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (524,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1046,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (137,' Colima');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (144,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (355,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (793,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (581,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (254,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (289,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (592,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (687,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1062,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (459,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (360,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (702,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (899,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (334,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (82,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (337,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (438,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (911,' Baja California Sur');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (741,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (63,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (494,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (514,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (837,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (833,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (535,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (386,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (888,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (555,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1030,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (346,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (644,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (895,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1058,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1062,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (974,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (635,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (923,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (518,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (101,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (763,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (693,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (249,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1170,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (944,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (289,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (921,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (498,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1077,' Zacatecas');
 INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (405,' Tabasco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (24,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (590,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1020,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (175,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (13,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (650,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (817,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (158,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (790,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (250,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (378,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (156,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (296,' San Luis Potosí');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (661,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (767,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (246,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (639,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1026,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (401,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (139,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (926,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1149,' Chihuahua');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (54,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (255,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (798,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (910,' Veracruz de Ignacio de la Llave');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (291,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (593,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (547,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1141,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (619,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (490,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1062,' Zacatecas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (645,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (946,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (931,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (334,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (877,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (762,' Coahuila de Zaragoza');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1069,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (553,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (242,' Sonora');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (688,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (582,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (677,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (517,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (148,' Michoacán de Ocampo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (663,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (350,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (994,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (27,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (335,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (442,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1141,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1129,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (817,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (419,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (783,' Distrito Federal');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (535,' Colima');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (196,' Jalisco');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (378,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (161,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (459,' Yucatán');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (356,' Baja California Sur');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (226,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (877,' Chiapas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (305,' Guerrero');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (98,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (353,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1114,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (517,' Oaxaca');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (368,' Guanajuato');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (94,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1098,' Colima');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1072,' Durango');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (762,' Hidalgo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (831,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (872,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (485,' Tamaulipas');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (912,' Campeche');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (741,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (163,' Quintana Roo');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (1104,' Sinaloa');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (837,' Morelos');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (617,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (144,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (907,' Oaxaca');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (169,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (488,' Puebla');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (165,' Nuevo León');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (861,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (71,' Tlaxcala');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (412,' Baja California');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (276,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (551,' Querétaro');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (951,'Aguascalientes');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (791,' Nayarit');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (408,' México');
INSERT INTO ATM (nIdSucursal_ATM,sEstado) VALUES (599,' Chihuahua');
