--Registro de Cajeros automaticos
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (289,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (226,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (81,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (209,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (20,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (135,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (65,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (43,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (36,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (124,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (59,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (101,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (203,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (49,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (299,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (206,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (242,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (50,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (297,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (139,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (237,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (199,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (88,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (145,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (169,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (193,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (30,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (258,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (23,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (29,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (151,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (59,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (220,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (293,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (255,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (16,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (69,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (275,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (249,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (151,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (297,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (267,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (196,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (150,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (288,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (203,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (92,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (61,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (227,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (65,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (11,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (128,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (103,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (200,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (1,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (232,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (263,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (99,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (250,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (165,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (286,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (282,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (185,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (144,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (138,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (62,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (263,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (265,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (210,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (101,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (83,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (132,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (180,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (230,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (232,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (27,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (36,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (89,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (19,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (252,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (100,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (243,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (299,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (252,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (111,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (107,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (128,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (152,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (4,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (66,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (82,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (139,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (96,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (9,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (294,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (102,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (88,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (240,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (236,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (272,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (288,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (13,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (81,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (72,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (214,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (30,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (49,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (65,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (280,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (88,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (296,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (209,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (140,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (188,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (75,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (85,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (265,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (71,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (84,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (50,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (6,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (293,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (177,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (79,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (228,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (104,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (156,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (278,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (218,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (137,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (228,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (182,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (167,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (188,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (282,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (232,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (73,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (190,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (196,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (139,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (80,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (46,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (13,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (121,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (260,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (296,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (259,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (44,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (57,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (168,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (49,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (46,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (247,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (11,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (85,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (25,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (45,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (134,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (14,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (8,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (48,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (63,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (188,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (177,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (174,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (38,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (278,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (177,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (42,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (117,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (113,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (27,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (215,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (266,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (287,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (178,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (258,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (36,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (245,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (215,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (271,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (32,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (82,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (17,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (286,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (176,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (5,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (173,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (61,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (161,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (218,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (225,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (31,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (65,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (213,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (233,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (236,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (272,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (288,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (13,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (81,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (72,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (214,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (30,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (49,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (65,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (280,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (88,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (296,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (209,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (140,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (188,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (75,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (85,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (265,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (71,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (84,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (50,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (6,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (293,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (177,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (79,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (228,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (104,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (156,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (278,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (218,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (137,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (228,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (182,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (167,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (188,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (282,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (232,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (73,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (190,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (196,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (139,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (80,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (46,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (13,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (121,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (260,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (296,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (259,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (44,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (57,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (168,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (49,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (46,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (247,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (11,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (85,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (25,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (45,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (134,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (14,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (8,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (48,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (63,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (188,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (177,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (174,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (38,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (278,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (177,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (42,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (117,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (113,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (27,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (215,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (266,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (287,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (178,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (258,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (36,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (35,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (245,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (215,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (271,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (32,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (82,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (17,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (286,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (176,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (5,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (173,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (61,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (161,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (218,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (225,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (31,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (65,'en servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (213,'fuera de servicio');
INSERT INTO atm (nidsucursal_atm,sestado) VALUES (233,'fuera de servicio');