INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (23,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (143,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (174,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (181,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (12,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (42,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (203,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (298,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (281,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (88,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (272,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (184,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (217,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (180,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (230,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (199,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (227,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (124,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (242,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (149,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (156,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (98,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (142,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (32,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (232,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (43,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (128,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (113,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (238,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (139,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (295,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (243,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (52,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (242,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (30,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (285,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (63,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (54,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (253,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (116,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (176,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (87,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (300,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (60,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (227,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (247,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (208,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (292,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (57,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (158,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (264,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (182,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (239,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (228,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (175,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (258,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (102,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (119,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (155,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (207,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (246,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (281,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (247,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (108,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (162,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (117,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (73,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (265,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (195,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (187,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (12,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (49,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (204,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (85,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (269,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (194,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (64,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (41,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (57,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (226,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (232,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (126,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (46,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (87,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (274,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (181,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (245,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (22,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (233,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (287,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (131,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (180,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (68,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (76,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (39,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (299,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (81,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (160,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (14,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (273,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (73,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (268,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (110,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (150,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (199,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (174,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (33,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (79,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (247,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (112,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (36,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (174,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (261,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (192,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (28,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (248,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (6,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (40,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (237,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (53,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (7,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (253,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (141,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (102,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (289,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (115,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (130,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (187,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (6,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (87,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (62,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (33,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (154,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (240,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (63,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (244,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (90,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (125,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (103,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (40,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (9,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (158,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (121,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (209,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (263,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (90,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (225,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (12,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (118,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (267,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (76,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (68,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (248,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (70,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (228,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (74,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (135,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (77,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (2,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (49,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (121,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (74,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (109,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (95,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (149,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (248,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (206,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (147,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (108,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (111,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (278,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (211,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (55,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (36,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (100,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (288,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (114,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (89,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (288,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (30,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (68,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (4,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (63,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (109,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (194,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (60,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (226,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (231,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (240,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (99,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (175,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (7,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (123,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (235,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (247,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (131,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (81,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (251,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (85,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (63,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (274,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (4,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (292,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (4,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (287,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (38,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (104,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (63,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (113,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (24,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (105,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (137,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (34,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (68,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (291,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (164,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (296,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (182,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (109,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (106,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (213,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (9,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (89,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (39,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (202,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (55,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (33,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (296,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (110,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (118,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (185,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (153,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (212,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (239,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (189,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (39,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (202,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (161,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (186,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (58,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (251,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (39,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (24,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (117,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (218,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (144,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (257,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (193,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (244,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (271,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (3,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (5,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (73,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (38,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (291,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (45,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (259,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (110,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (3,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (222,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (35,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (66,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (202,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (208,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (143,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (86,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (217,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (10,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (265,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (117,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (177,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (43,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (65,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (191,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (47,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (44,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (283,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (144,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (221,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (203,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (14,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (246,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (136,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (167,'fuera de servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (97,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (41,'en servicio');
INSERT INTO "ventanilla" (nidsucursal_v,sestado) VALUES (243,'en servicio');

