INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (75,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (70,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (271,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (299,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (174,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (260,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (247,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (173,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (258,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (198,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (105,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (211,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (143,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (60,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (3,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (194,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (289,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (116,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (171,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (9,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (21,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (184,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (88,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (174,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (12,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (141,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (58,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (51,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (101,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (71,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (140,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (148,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (267,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (232,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (198,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (293,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (160,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (243,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (153,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (182,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (166,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (223,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (239,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (71,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (82,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (295,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (294,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (204,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (191,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (60,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (290,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (163,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (280,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (217,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (269,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (154,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (138,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (212,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (54,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (189,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (300,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (195,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (58,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (16,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (71,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (244,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (78,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (290,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (33,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (13,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (85,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (122,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (291,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (59,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (47,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (23,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (72,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (235,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (116,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (181,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (38,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (249,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (299,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (174,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (57,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (300,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (232,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (290,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (140,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (221,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (287,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (289,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (178,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (214,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (107,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (229,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (32,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (117,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (46,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (2,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (101,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (138,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (240,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (266,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (181,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (248,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (231,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (170,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (9,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (241,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (187,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (11,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (267,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (125,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (168,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (228,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (71,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (165,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (171,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (88,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (64,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (8,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (92,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (206,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (233,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (242,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (162,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (278,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (14,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (119,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (156,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (46,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (130,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (17,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (248,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (61,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (15,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (35,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (210,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (283,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (45,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (211,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (153,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (85,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (253,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (25,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (270,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (102,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (58,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (224,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (180,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (287,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (120,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (152,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (267,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (58,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (178,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (221,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (210,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (215,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (268,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (102,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (109,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (39,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (197,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (52,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (58,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (64,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (227,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (208,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (225,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (57,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (210,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (277,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (237,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (8,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (259,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (252,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (259,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (20,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (67,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (159,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (178,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (2,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (81,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (236,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (4,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (81,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (61,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (156,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (29,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (83,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (192,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (59,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (155,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (125,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (211,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (29,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (42,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (84,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (173,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (255,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (148,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (209,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (292,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (231,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (148,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (78,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (100,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (289,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (129,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (207,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (118,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (127,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (54,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (21,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (294,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (40,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (266,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (112,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (77,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (226,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (154,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (243,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (8,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (194,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (286,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (272,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (178,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (154,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (216,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (165,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (159,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (225,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (34,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (183,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (26,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (160,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (109,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (46,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (62,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (275,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (61,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (268,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (229,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (171,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (91,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (181,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (244,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (73,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (138,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (257,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (120,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (50,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (290,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (99,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (105,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (174,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (284,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (167,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (110,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (292,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (101,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (96,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (28,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (155,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (165,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (257,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (5,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (121,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (262,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (12,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (182,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (216,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (259,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (228,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (152,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (208,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (185,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (123,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (127,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (233,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (205,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (256,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (165,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (74,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (280,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (236,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (62,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (67,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (159,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (46,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (200,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (216,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (97,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (44,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (226,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (224,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (288,'en servicio');
INSERT INTO ventanilla (nidsucursal_v,sestado) VALUES (150,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (112,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (14,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (157,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (190,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (268,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (129,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (25,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (1,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (1,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (10,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (101,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (102,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (103,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (103,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (103,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (104,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (106,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (107,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (107,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (109,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (109,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (110,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (111,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (112,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (113,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (113,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (114,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (115,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (115,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (117,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (118,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (119,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (12,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (121,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (122,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (123,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (123,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (124,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (125,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (126,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (126,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (128,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (128,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (13,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (13,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (130,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (131,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (132,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (133,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (134,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (134,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (135,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (139,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (140,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (140,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (141,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (144,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (145,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (148,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (148,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (149,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (15,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (15,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (150,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (150,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (151,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (155,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (158,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (16,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (160,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (160,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (160,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (163,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (166,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (166,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (167,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (168,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (169,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (17,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (173,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (175,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (178,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (18,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (180,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (181,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (182,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (184,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (184,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (186,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (189,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (189,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (19,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (19,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (190,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (190,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (191,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (192,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (195,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (196,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (197,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (197,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (197,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (199,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (199,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (20,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (20,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (201,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (204,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (205,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (206,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (206,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (207,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (207,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (209,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (21,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (21,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (210,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (211,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (212,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (213,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (213,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (213,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (214,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (214,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (215,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (216,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (217,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (219,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (219,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (22,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (221,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (223,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (223,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (224,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (225,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (227,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (227,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (227,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (227,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (229,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (229,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (23,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (231,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (231,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (232,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (236,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (236,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (239,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (239,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (24,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (24,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (24,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (243,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (244,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (244,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (244,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (245,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (249,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (25,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (251,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (252,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (253,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (253,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (253,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (253,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (254,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (255,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (256,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (257,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (258,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (260,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (262,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (264,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (267,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (269,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (272,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (273,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (273,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (274,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (278,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (278,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (279,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (28,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (28,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (28,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (28,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (281,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (283,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (283,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (285,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (286,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (287,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (288,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (289,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (29,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (29,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (29,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (29,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (290,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (290,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (291,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (291,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (292,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (292,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (294,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (294,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (295,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (295,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (295,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (297,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (298,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (299,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (299,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (3,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (30,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (300,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (31,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (31,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (33,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (34,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (35,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (37,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (38,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (4,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (42,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (42,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (43,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (43,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (44,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (45,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (45,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (46,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (49,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (5,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (5,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (5,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (52,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (53,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (54,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (55,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (55,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (55,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (56,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (56,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (57,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (58,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (6,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (60,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (61,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (63,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (64,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (64,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (66,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (66,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (68,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (68,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (68,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (69,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (69,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (69,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (7,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (7,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (70,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (71,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (72,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (72,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (73,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (76,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (77,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (79,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (8,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (8,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (80,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (80,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (80,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (81,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (81,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (82,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (83,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (86,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (87,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (87,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (87,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (87,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (88,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (89,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (89,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (89,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (9,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (90,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (90,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (90,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (93,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (93,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (96,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (96,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (96,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (97,'en servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (97,'fuera de servicio');
INSERT INTO ventanilla (nidsucursal_v, sestado) VALUES (98,'en servicio');